### ISSUE TITLE
Maximum of 65535 frames/

### ISSUE THREAD

**Issue by 12mholmes** [roguelike2d/TekkenBot#10]
Noticed in the TekkenGameState you're capping out of 65535 frames of gamedata, is there a reason here?

Another aside, is that if I remember correctly (at work rn) rage arts show the improper amount of startup frames (probably because of the super flash). Is this because you're missing another "ComplexMoveState" for rage art startup?

Nice job with this btw, if you want any help let me know

**Comment by roguelike2d** [comment]
Yeah, that's because the number I'm using to order frames caps at 0xFFFF.  I don't actually know what that number is, it's not the game timer, just something that goes up 1 each frame and doesn't reset. At some point I need to replace it with the actual in game frame counter, but I haven't found it yet.

Rage move startup is definitely including the super flash frames right now, I haven't looked into to sorting it out yet so I don't know how easy/difficult it'll be to fix.

**Comment by 12mholmes** [comment]
I have a fork where i've found static values for frame count (which I get as an 8byte number, probably more than enough frames), and I've also found static memory addresses for player1/player2 data. After making these changes, I get the block and hit frames and damage to show up perfectly, but startup and attack type(mid/high etc) aren't updating properly. I've tried scanning for startup values, but I can only find the 8 offset values, which are how the current app works. To get move startup frames, did you just scan for 11 while doing an i11 move etc. If not, let me know so I can try to figure that out.
