### ISSUE TITLE
If you have fps drops, please post your information here

### ISSUE THREAD

**Issue by roguelike2d** [roguelike2d/TekkenBot#11]
If you are experiencing fps drops that don't resolve when you lower your graphics settings while running this tool, please post:
* Your windows version
* Your game resolution
* The %cpu that is being used by TekkenBot FrameDataOverlay in the task manager and the %cpu being used by Tekken7.exe

**Comment by WAZAAAAA0** [comment]
It's a combination of Windows 7, VSync OFF, and transparency.

Windows 7 users can still disable VSync by using a non-Aero theme aka turning Desktop composition OFF (Win8 and Win10 can't do it anymore afaik).

Overlaying transparent stuff on windowed games with VSync OFF causes frame rate slowdowns. This can be caused by other programs too e.g. Skype notifications.

Users can work around the problem by enabling Aero, which isn't optimal for fighting games because of the added display lag.
You as the developer can probably solve it in two ways:
easy = get rid of anything transparent (coding wise, make sure you set the transparency to OFF and not just to 0)
hard = fancy DirectX injection of frame data display à la Frame Trapped (would also make the tools work in true Full Screen and not just Windowed/Borderless)

I've just made a simple program that lets you toggle the transparency of an always-on-top dummy window to quickly spot the frame rate drops in a Win7+transparent window overlay+VSync OFF scenario for testing purposes as a proof: http://www.mediafire.com/file/6p7gagzji2mv9vl/TransToggle.zip

**Comment by roguelike2d** [comment]
Wow, that is the best issue report I've ever seen.

I'm reluctant to mess with the dll, especially since I haven't had to so far and there's multiple other people going down that path.

Tkinter without transparency is pretty ugly but I can add a config option to the next release to disable transparency for users having frame rate issues.

**Comment by WAZAAAAA0** [comment]
Just wanted to confirm that setting transparency = 0 in frame_data_overlay.config fixed the issue.
