### ISSUE TITLE
No fight detected. Gamestate not updated

### ISSUE THREAD

**Issue by aciko11** [roguelike2d/TekkenBot#15]
It does find the game, but it does not detect the fight when i'm in practice mode. Tried to run as administrator and tried with older versions too. Got windows 10 64 bit and the game is 64 bit too

**Comment by roguelike2d** [comment]
Here's a video describing how to use cheat engine to find the value that will make TekkenBot work for folks with this problem. https://youtu.be/wqY3A6R-gVM

If anyone gets this to work successfully and posts that memory offset, I'll add it to the config file.

**Comment by WAZAAAAA0** [comment]
The process can probably be simplified a tiny little bit:

1. enter a training match with any side, character, stage
2. make sure both characters are simply standing
3. Value Type: Array of byte - New Scan: 01 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 FF FF FF FF
4. Pointer scan the first found address just like the video. Optionally, reduce Max level to 2 since the offets are always 31C and 0 in order to reduce the chances of getting multiple Pointer paths
5. add it to memory_address.config
