### ISSUE TITLE
UI suggestion

### ISSUE THREAD

**Issue by biejis** [roguelike2d/TekkenBot#23]
![fd1](https://user-images.githubusercontent.com/29903063/27843569-26a3e302-60e3-11e7-8a63-fc32f5d54b9d.png)
![fd2](https://user-images.githubusercontent.com/29903063/27843630-c390f100-60e3-11e7-9f55-ed31d7622acd.png)
![fd3](https://user-images.githubusercontent.com/29903063/27843631-c39ce988-60e3-11e7-90a7-31a5ab652f1c.png)
0
S=start
D=damage
A=active
T=total

future
CW=cancel window
BW=buffer window

**Comment by roguelike2d** [comment]
Yeah the UI definitely needs some work. The log of past moves is actually kinda important though because multi-hitting moves have a lot of their important information on the first hit. I also kinda like having things in the same order as the wiki, although that may be because I'm used to using the wiki.

The below the lifebar version seems like it might be getting a little too close to the action, especially big characters like Kuma or Gigas are going to be constantly running into it.

One of the very early versions actually displayed total frames but it wasn't very useful and I found myself mostly just getting confused by it. If anyone can give a common use case for it, I'll put it back in there.

Cancel Window is a good idea. Does the buffer window change based on the move, I thought it was 8 frames across the board.

**Comment by benjimmy** [comment]
Total frames could be useful because some moves are deceptively quick to recover on whiff and people use them at range to bait counter hits.

**Comment by biejis** [comment]
![fd6](https://user-images.githubusercontent.com/29903063/27940572-6ffa4dd6-6299-11e7-92c4-27ec70369375.jpg)
![fd4](https://user-images.githubusercontent.com/29903063/27940573-70218608-6299-11e7-8394-13c62ea65389.jpg)
vs gigas
