### ISSUE TITLE
Hey could you email me

### ISSUE THREAD

**Issue by aeonsnake** [roguelike2d/TekkenBot#35]
joseph.bozzi16@gmail.com

**Comment by roguelike2d** [comment]
No. But I would be happy to reply to any questions you have in this public forum.

**Comment by aeonsnake** [comment]
okay , well what are having trouble with the bot?

**Comment by roguelike2d** [comment]
I'd like to hook it up to a learning algorithm that produces interesting results in a reasonable amount of time. However:
1. While python deep learning libraries are better than most other languages, they are mostly optimized for non-windows environments, but Tekken 7 only runs on windows.
1. I've got a pretty limited pool of available data to train the algorithm on and basically no 'good' data. Like trying to train a self-driving car by recording a bunch of orangutans driving around.
1. It's not clear what restrictions are required to make the resulting behavior 'interesting'. Without any restrictions, a good algorithm could learn to play 'perfectly' like ToolAssisted's parry bot, but I'd rather something that played rock-paper-scissors by learning player tendencies instead of by reading the microsecond before what the opponent chose and beating it.
1. In fact, it's not clear that general learning is the way to go at all, it might be better to tailor make an AI that knows quite a bit about fighting games in general and possibly Tekken specificially and then only train, say, the movement on a learning algorithm.
1. I quite like the kind of api https://gym.openai.com/ uses where the input is a state and the output is selected from a list of available actions, but I don't really want to pass in the entire screen as the input and it's unclear what a complete Tekken 7 'state' should consist of. Likewise, available actions could either be button presses or something slightly more granular (backdash, input a string, etc.).

**Comment by aeonsnake** [comment]
well couldn't you make it just avoid the person and look for a window and
just chain combos? i couldn't run it from the setup.bat it gave me errors,
I have py3. toolassited has his sf5 bot on his got. I am currently afk but
this is super interesting.

**Comment by roguelike2d** [comment]
It kinda depends on how you measure a successful Tekken Bot. So, on one hand I've got FrameTrapBot which currently blocks everything. I could make it sidestep unblockables and fireballs, tech throws and have it walk toward you like the terminator then do either some basic punish or basic mixup that I prerecorded for it. That would probably be enough perform very well online.

But, that's sort of an intelligent keyboard macro. It's not really playing Tekken or using any Tekken skills, its the pinnacle result of what people mean when they complain about CPU opponents 'reading buttons' and not being fun or useful to fight against. Its much easier to make this work in Tekken than in SF5 due to the much larger frame counts masking any kind of network delay.

So if the goal is do well in Online Ranked, that might work, but I'd rather aim for something that is either a) fun/interesting to play against so that people want to rematch it or b) helps people play Tekken better in some way. Of course, both those goals are pretty ambiguous and ill defined so who knows.
