### ISSUE TITLE
Help understanding chardata 

### ISSUE THREAD

**Issue by JABirchall** [roguelike2d/TekkenBot#40]
So, I am working on writing up ALOT of combo's in the chardata, but I am having trouble understanding the config orders, So I have a few questions.

Question 1, Am I correct in assuming the ${Char}.txt is loaded based n the char the bot is controlling? making each of the punishes listed for char id's the bot is against? or is it the other way around.

Question 2, How do you define default combos for a char if it has no specific punish for the target? I read the defaults.txt if I list the combo under the char ID the bot is playing is that how it reads it?

Question 3, What are the possible inputs for the combo's? like how to I tell it to wait a few frames or sprint etc etc.

**Comment by excision1** [comment]
https://github.com/roguelike2d/TekkenBot/issues/18#issuecomment-313352508  answer to question 3


say bot is using kazuya it loads kazuya.txt and i think if nothing is in the text file it loads default.txt and edit the text in the file to change the combos etc but ya best waiting on roguelike2d to answer i guess :P

**Comment by roguelike2d** [comment]
First, this is not a released or supported feature so be warned that notation is ***subject to change*** (and there's a pretty good chance that change will hose all your combos). Indeed, many of the combos currently in the CharacterData files have been broken by notation changes.

There's a brief intro to notation at https://github.com/roguelike2d/TekkenBot/issues/18#issuecomment-313352508

1. The punishes are for the character the bot is controlling. So if it's controlling Alisa, it loads Alisa.txt. Well it doesn't actually know character names so it actually scans for a file with the right character id, which happens to exist in Alisa.txt but close enough.

1. Default.txt is only loaded if ${Char}.txt doesn't exist or if something else goes wrong.  Right now there's no way to say 'everyone's -11 ws punish is +4 unless specified otherwise'.

2. see the link above and check the character files.
