### ISSUE TITLE
Any Eta/news on Ai

### ISSUE THREAD

**Issue by excision1** [roguelike2d/TekkenBot#43]
as title says wondering when the ai side of things might be getting some love can understand you're busy working  solo on the tekkenbotprime aka frame data overlay and ofc real life ;) just thought id ask if u had plans on the ai side of things any time soon

**Comment by roguelike2d** [comment]
It's on indefinite hold until I or someone else can think of a specific use case for it. When I started this project AI seemed cool enough that it was it's own end, but now that I know more about how Tekken works and the ease with which a tailored AI is going to 'master' the game, I'm more interested in creating something that would be useful to helping people understand Tekken better rather than just be really good at beating people.

**Comment by excision1** [comment]
yeah i get how u mean cant exactly learn from something what blocks 100% of attacks etc could be a good sparring partner if it had features like says i dunno 80% block on highs  10% low parry chance 35% low block chance with the punish type feature etc can imagine something along them lines been of some use for training purposes get u out of habits of hitting framed moves into blocks etc spamming lows and stuff but can imagine that been a right hassle to make doable :P but thanks for the response was really curious cus i loved the idea of a crazy ai what auto punishes been enjoying testing moves into character data mainly on the auto punishers for pure pass time
